---
title: 'Natural Language Processing Lab 5'
format:
  html:
    code-fold: true
    code-tools: true
jupyter: python3
toc: true
toc-depth: 2
number-sections: true
author: 'Lonny Chen'
date: '2026-09-30'
embed-resources: true
---

# Objectives
Welcome to the fifth Natural Language Processing lab.

Today's objectives are to:

1. Classify text using the **linear models** of Naive Bayes, Logistic Regression, and Linear SVM.
2. Observe how different **preprocessing and representation options** affect classification performance.
3. Inspect **word-feature model weights** for interpretation of results.
4. Explore classification **performance metrics** and cost trade-offs.

# Notebook Setup

## Packages

In [1]:
#| code-summary: 'Import packages'
#| output: false
# Dataset packages
from datasets import load_dataset
import kagglehub
from kagglehub import KaggleDatasetAdapter
from imblearn.under_sampling import RandomUnderSampler

# Data packages
import pandas as pd
pd.set_option('display.max_colwidth', None) #default: 50 chars
pd.set_option('display.max_columns', None) #default: 20 columns
import numpy as np

# NLP packages
import spacy
import gensim.downloader as api
from gensim.models import Word2Vec, KeyedVectors
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Classification libraries
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import make_scorer, f1_score, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Datasets

In [2]:
#| code-summary: 'Dataset #1: Spam Detection'
ds = load_dataset('ucirvine/sms_spam')
df = ds['train'].to_pandas()
df = df.rename(columns={'sms': 'text', 'label': 'y'})
df.sample(2)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Serenity\.cache\huggingface\hub\datasets--ucirvine--sms_spam. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Serenity\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 5574/5574 [00:00<00:00, 39291.33 examples/s]

,text,y
4387,", im .. On the snowboarding trip. I was wondering if your planning to get everyone together befor we go..a meet and greet kind of affair? Cheers, \n",0
1589,At 4. Let's go to bill millers\n,0

In [9]:
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "crowdflower/twitter-airline-sentiment/versions/4",
    "Tweets.csv",
    pandas_kwargs={"encoding": "latin-1"},
)

Downloading to C:\Users\Serenity\.cache\kagglehub\datasets\crowdflower\twitter-airline-sentiment\versions\4\Tweets.csv...

100%|██████████| 1.08M/1.08M [00:00<00:00, 4.31MB/s]

ValueError: Error reading file: Error tokenizing data. C error: Expected 1 fields in line 3, saw 4

In [10]:
df = df.rename(columns={"airline_sentiment": "y"})
df.sample(2)

,text,y
5103,Nope thats fine. I might have a nap tho! \n,0
2371,"That day ü say ü cut ur hair at paragon, is it called hair sense? Do ü noe how much is a hair cut? \n",0

In [11]:
#| code-summary: 'Dataset #3: Authorship Detection'
ds = load_dataset('CogniSAL/MDAIGT')
df = pd.concat([ds['train_news'].to_pandas(), ds['train_news'].to_pandas()])
df = df.rename(columns={'label': 'y'})
df = df.sample(frac=0.1, random_state=42) # reduce for vectorizing time
df.sample(2)

c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Serenity\.cache\huggingface\hub\datasets--CogniSAL--MDAIGT. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train_news split: 100%|██████████| 10000/10000 [00:00<00:00, 29057.59 examples/s]
Generating train_academic_articles split: 100%|██████████| 10000/10000 [00:00<00:00, 43582.94 examples/s]

,id,text,y
8197,8198,"Biker Robert Reed and His Canine Companions A Journey Across America Robert Reed, an avid motorcycle enthusiast from Pennsylvania, embarked on an unprecedented adventure over two years ago when he set out to traverse the United States with his two loyal dogs, Andy and Maddie. Dressed in miniature leather jackets and goggles, the duo rode sidecar with Reed, experiencing the country's breathtaking landscapes and historic landmarks. This unique trio, often referred to as ""The Biking Bulldogs,"" has since visited 22 states and covered approximately 15,000 miles. Their journey has taken them from the sunny beaches of California to the majestic Rocky Mountains, the iconic Gateway Arch in St. Louis, and the beautiful vineyards of Napa Valley, among other memorable destinations. Andy, a 7-year-old English bulldog with a regal demeanor and distinctive wrinkled features, and Maddie, a lively 5-year-old English bulldog with boundless energy, are seldom seen without their distinctive outfits. These protective garments, custom-made by a local seamstress, shield them from the elements, ensuring they remain comfortable and content throughout their travels. ""I always wanted to see the country, and I knew I couldn't do it alone,"" Reed shared. ""Having my dogs with me makes every mile worthwhile. They're not just my companions, but they're my family."" Reed, a retired firefighter, had previously taken shorter motorcycle trips with his late wife, who passed away due to an illness. Struggling with the grief, he decided to take on this ambitious journey to rediscover the joy of exploration and to honor his wife's memory. As they continued their travels, Reed documented their experiences on social media, amassing a devoted following of over 100,000 people. Their heartwarming stories of adventure, love, and loyalty have inspired countless individuals and touched the lives of many. ""The Biking Bulldogs"" have also used their platform to promote animal welfare and adoption, which is close to Reed's heart. He often shares stories of other rescued animals he's encountered on his travels and encourages his followers to adopt from shelters. As Reed and his faithful companions prepare for the final leg of their journey, they look forward to visiting the remaining states and making new memories. Their epic adventure serves as a testament to the indomitable human spirit and the unbreakable bond between man and man's best friend.",machine
6775,6776,"(CNET) -- Coulomb Technologies on Wednesday said it will build 4,600 electric vehicle charging stations in nine regions of the U.S., funded by $37 million in grants. More than half of the charging stations in the program called ChargePoint America will go in public locations, such as overnight parking spaces, offices, or retail locations. About 2,000 going into people's homes as part of the purchase of an electric vehicle. The goal of the charging network and others like it is to make electric vehicles more accessible to consumers, as these cars come to market in the coming months, said Richard Lowenthal, the CEO of Campbell, California-based Coulomb Technologies during a press conference. The program differs from other electric vehicle charging networks in that Coulomb is working with Ford Motor, General Motors, and Smart USA on the roll out, Lowenthal said. Ford will release an electric Transit Connect utility van and electric Ford Focus sedan in 2011, GM plans to release the Volt by November, and the electric Smart fortwo will begin pilot testing in the U.S. by 2011. The stations themselves will be equipped with 220-volt service at either 16 or 30 amps, which enables faster charging than regular home electrical service. Lowenthal said that an electric car with a large battery could charge from empty in under four hours. Drivers will be able to find available charging stations using either an iPhone or Blackberry application, which can also send alerts if a car battery is running low or if a connected car is unplugged. The system includes software for station owners to set billing rates. Regions are considering cheaper off-peak rates to encourage drivers to charge overnight. Utilities can see available energy electric vehicles or run demand-response programs to slow charging rates during peak times if needed. ""Our stations are unique in that they are all networked. That allows them to support a bunch of software applications which are important to different constituents,"" Lownenthal said, adding that installation will begin immediately and continue for 18 months. The nine regions are: the Bellevue and Redmond, Washington area; Sacramento, Calif.; the San Francisco and San Jose, California. region; Los Angeles; Orlando, Florida; Washington D.C.; New York City; Austin, Texas; and Detroit, Michigan. Of the total in grants, $15 million will come from the Department of Energy as part of the stimulus act and another $22 million will come from other sources, Lowenthal said. As part of project, Coulomb will gather data on driver usage patterns and report it to the Department of Energy until October 2013. © 2010 CBS Interactive Inc. All rights reserved. CNET, CNET.com and the CNET logo are registered trademarks of CBS Interactive Inc. Used by permission.",human

In [12]:
#| code-summary: 'Train-Test Split and class balancing'
RANDOM_SEED = 42
df_train, df_test = train_test_split(df, test_size=0.2, random_state=RANDOM_SEED)
print(df_train['y'].value_counts())
rus = RandomUnderSampler(random_state=42)
df_train_bal = pd.DataFrame()
df_train_bal['text'], df_train_bal['y'] = rus.fit_resample(df_train['text'].to_frame(), df_train['y'])
df_train_bal['y'].value_counts()

y
human      800
machine    800
Name: count, dtype: int64

y
human      800
machine    800
Name: count, dtype: int64

# Preprocessing

In [13]:
#| code-summary: 'Preprocessing from Lab 2'
nlp = spacy.load('en_core_web_sm')
def spacy_tokenizer(text):
    '''Tokenizes and normalizes one string of text'''
    doc = nlp(text) 
    # MODIFY BELOW: lower_, is_alpha, lemma_, is_stop (normalization from Lab 2)
    tokens = [token.text for token in doc if token.is_alpha]
    return tokens

# Pre-check test entry with all OOV else get_mean_vector error
tokens = df_train_bal['text'].apply(spacy_tokenizer)
df_train_bal = df_train_bal[tokens.str.len() > 0].copy()
tokens = df_test['text'].apply(spacy_tokenizer)
df_test = df_test[tokens.str.len() > 0].copy()

# Representation

## Count/TF-IDF

In [14]:
#| code-summary: 'Bag of Words from Lab 3'
bow_vectorizer = CountVectorizer(
    tokenizer = spacy_tokenizer,
    token_pattern = None,
    lowercase = False,
    min_df = 2
)
X_train_bow = bow_vectorizer.fit_transform(df_train_bal['text'])
X_test_bow = bow_vectorizer.transform(df_test['text'])
print(f'The vocabulary size is {len(bow_vectorizer.vocabulary_)} tokens\n')
pd.DataFrame(X_train_bow.toarray(), index=df_train_bal.index, columns=bow_vectorizer.get_feature_names_out()).head()

The vocabulary size is 15509 tokens

      A  ABC  AC  ACA  ACLU  AFP  AG  AIDS  AIDs  AM  AMIA  AP  AQAP  ATM  \
5903  1    0   0    0     0    0   0     0     0   0     0   0     0    0
9826  0    0   0    0     0    0   0     0     0   0     0   0     0    0
8632  1    0   0    0     0    0   0     0     0   0     0   0     0    0
3138  0    0   0    0     0    0   0     0     0   0     0   0     0    0
9381  0    0   0    0     0    0   0     0     0   0     0   0     0    0

      ATOL  ATP  Aaron  Aasiya  Abaaoud  Abbey  Abdel  Abdelhamid  Abdul  \
5903     0    0      0       0        0      0      0           0      0
9826     0    0      0       0        0      0      0           0      0
8632     0    0      0       0        0      0      0           0      0
3138     0    0      0       0        0      0      0           0      0
9381     0    0      0       0        0      0      0           0      0

      AbdulMutallab  Abdulaziz  Abdullah  Abe  Abed  Aberdeen  Abhishek  \
5903              0          0         0    0     0         0         0
9826              0          0         0    0     0         0         0
8632              0          0         0    0     0         0         0
3138              0          0         0    0     0         0         0
9381              0          0         0    0     0         0         0

      About  Above  Abraham  Abrahams  Abrams  Abu  Abzug  Academy  Accord  \
5903      0      0        0         0       0    0      0        0       0
9826      0      0        0         0       0    0      0        0       0
8632      0      0        0         0       0    2      0        0       0
3138      0      0        0         0       0    0      0        0       0
9381      0      0        0         0       0    0      0        0       0

      According  Accra  Accused  Achieve  Achievement  Across  Act  Acting  \
5903          0      0        0        0            0       0    0       0
9826          0      0        0        0            0       0    0       0
8632          0      0        0        0            0       0    0       0
3138          1      0        0        0            0       0    0       0
9381          0      0        0        0            0       0    0       0

      Action  Actions  Active  Activist  Activities  Actor  Actors  Actress  \
5903       0        0       0         0           0      0       0        0
9826       0        0       0         0           0      0       0        0
8632       0        0       0         0           0      0       0        0
3138       0        0       0         0           0      0       0        0
9381       0        0       0         0           0      0       0        0

      Actually  Adam  Adding  Additional  Additionally  Adele  Adidas  \
5903         0     0       0           0             0      0       0
9826         0     0       0           0             0      0       0
8632         0     0       0           0             0      0       0
3138         0     0       0           0             0      0       0
9381         0     0       0           0             0      0       0

      Administration  Administrator  Adolf  Adrian  Advanced  Adventures  \
5903               0              0      0       0         0           0
9826               0              0      0       0         0           0
8632               0              0      0       0         0           0
3138               0              0      0       0         0           0
9381               0              0      0       0         0           0

      Advocates  Affairs  Affleck  Affordable  Afghan  Afghanistan  Africa  \
5903          0        0        0           0       0            0       0
9826          0        0        0           0       0            0       0
8632          0        0        0           0       0            0       0
3138          0        0        0           0       0            0       0
9381          0        0        0           0       0            0       0

      African  After  Afterwards  Again  Against  Agatha  Age  Agency  Agent  \
5903        0      0           0      0        0       0    0       0      0
9826        0      1           0      0        0       0    0       0      0
8632        1      0           0      0        0       0    0       0      0
3138        0      0           0      0        0       0    0       0      0
9381        0      0           0      0        0       0    0       0      0

      Agree  Agriculture  Ah  Ahlers  Ahmed  Aid  Air  AirAsia  Airbus  Aires  \
5903      0            0   0       0      0    0    0        0       0      0
9826      0            0   0       0      0    0    0        0       0      0
8632      0            0   0       0      0    0    0        0       0      0
3138      0            0   0       0      0    0    0        0       0      0
9381      0            0   0       0      0    0    0        0       0      0

      Airline  Airlines  Airplane  Airport  Airways  Akaichi  Akka  Al  \
5903        0         0         0        0        0        0     0   0
9826        0         0         0        0        0        0     0   0
8632        0         0         0        0        0        0     0   0
3138        0         0         0        0        0        0     0   0
9381        0         0         0        0        0        0     0   0

      Alabama  Alain  Alamuddin  Alan  Alaska  Alaskan  Alba  Albert  Alberto  \
5903        0      0          0     0       0        0     0       0        0
9826        0      0          0     0       0        0     0       0        0
8632        0      0          0     0       0        0     0       0        0
3138        0      0          0     0       0        0     0       0        0
9381        0      0          0     0       0        0     0       0        0

      Albie  Album  Alcohol  Alec  Alejandro  Aleppo  Alert  Alex  Alexa  \
5903      0      0        0     0          0       0      0     0      0
9826      0      0        0     0          0       0      0     0      0
8632      0      0        0     0          0       0      0     0      0
3138      0      0        0     0          0       0      0     0      0
9381      0      0        0     0          0       0      0     0      0

      Alexander  Alexandre  Alexandria  Alexis  Alfie  Algeria  Ali  Alice  \
5903          0          0           0       0      0        0    0      0
9826          0          0           0       0      0        0    0      0
8632          1          0           0       0      0        0    0      0
3138          0          0           0       0      0        0    0      0
9381          0          0           0       1      0        0    0      0

      Alison  Alito  Alive  All  Allegations  Allen  Alliance  Allred  Almost  \
5903       0      0      0    0            0      0         0       0       0
9826       0      0      0    0            0      0         0       0       0
8632       0      0      0    0            0      0         0       0       0
3138       0      0      0    0            1      0         0       0       0
9381       0      0      0    0            0      0         0       0       0

      Along  Alongside  Alonso  Alpine  Also  Alternatives  Although  Always  \
5903      0          0       0       0     0             0         0       0
9826      0          0       0       0     0             0         0       0
8632      0          0       0       0     0             0         0       0
3138      0          0       0       0     0             0         0       0
9381      0          0       0       0     0             0         0       0

      Alzheimer  Amal  Amanda  Amazon  Amber  Ambrose  Amedy  Amelia  \
5903          0     0       0       0      0        0      0       0
9826          0     0       0       0      0        0      0       0
8632          0     0       0       0      0        0      0       0
3138          0     0       0       0      0        0      0       0
9381          0     0       0       0      0        0      0       0

      Amendment  America  American  Americans  Americas  Amid  Amidst  Among  \
5903          0        0         1          0         0     0       0      0
9826          0        0         1          0         0     0       0      0
8632          0        0         0          0         0     0       0      0
3138          0        0         3          3         0     0       0      1
9381          0        0         0          0         0     0       0      0

      Amphipolis  Amsterdam  Amy  An  Ana  Anadappa  Analysis  Analysts  \
5903           0          0    0   0    0         0         0         0
9826           0          0    0   0    0         0         0         0
8632           0          0    0   0    0         0         0         0
3138           0          0    0   1    0         0         0         0
9381           0          0    0   0    0         0         0         0

      Analytics  Anchorage  And  Anderlecht  Anders  Andersen  Anderson  \
5903          0          0    0           0       0         0         0
9826          0          0    0           0       0         0         0
8632          0          0    0           0       0         0         0
3138          0          0    0           0       0         0         0
9381          0          0    0           0       0         0         0

      Andre  Andrea  Andrew  Android  Andy  Anfield  Angel  Angela  Angeles  \
5903      0       0       0        0     0        0      0       0        0
9826      0       0       0        0     0        0      0       0        0
8632      0       0       0        0     1        0      0       0        0
3138      0       0       0        0     0        0      0       0        0
9381      0       0       0        0     0        0      0       0        0

      Angelina  Angry  Angus  Animal  Aniston  Ankara  Ann  Anna  Annapolis  \
5903         0      0      0       0        0       0    1     0          0
9826         0      0      0       0        0       0    0     0          0
8632         0      0      0       0        0       0    0     0          0
3138         0      0      0       0        0       0    0     0          0
9381         0      0      0       0        0       0    0     0          0

      Anne  Annie  Announces  Annual  Another  Antarctic  Anthony  Anti  \
5903     0      0          0       0        1          0        0     0
9826     0      0          0       0        0          0        0     0
8632     0      0          0       0        0          0        0     0
3138     0      0          0       0        0          0        0     0
9381     0      0          0       0        0          0        0     0

      Antoine  Antonio  Any  Anybody  Anyone  Anytime  Apollo  App  Apparel  \
5903        0        0    0        0       0        0       0    0        0
9826        0        0    0        0       0        0       0    0        0
8632        0        0    0        0       0        0       0    0        0
3138        0        0    0        0       0        0       0    0        0
9381        0        0    0        0       0        0       0    0        0

      Apparently  Appeals  Apple  Applied  Apps  April  Apsley  Arab  Arabia  \
5903           0        0      0        0     0      0       0     0       0
9826           0        0      0        0     0      0       0     0       0
8632           0        0      0        0     0      0       0     0       0
3138           0        0      0        0     0      1       0     0       0
9381           0        0      0        0     0      0       0     0       0

      Arabian  Arch  Archaeologists  Archer  Archives  Arctic  Are  Aren  \
5903        0     0               0       0         0       0    0     0
9826        0     0               0       0         0       0    0     0
8632        0     0               0       0         0       0    0     0
3138        0     0               0       0         0       0    0     0
9381        0     0               0       0         0       0    0     0

      Arena  Argentina  Argentine  Argo  Arizona  Arkansas  Arlington  Armed  \
5903      0          0          0     0        0         0          0      0
9826      0          0          0     0        0         0          0      0
8632      0          0          0     0        0         0          0      0
3138      0          0          0     0        0         0          0      0
9381      0          0          0     0        0         0          0      0

      Army  Arnold  Around  Arpaio  Arquette  Arrest  Arrested  Arsenal  \
5903     0       0       0       0         0       0         0        0
9826     0       0       0       0         0       0         0        0
8632     0       0       0       0         0       0         0        0
3138     0       0       0       0         0       0         0        0
9381     0       0       0       0         0       0         0        6

      Arsene  Art  Arteta  Arthur  Article  Artists  Arts  Arturo  Artwalk  \
5903       0    0       0       0        0        0     0       0        0
9826       0    0       0       0        0        0     0       0        0
8632       0    0       0       0        0        0     0       0        0
3138       0    0       0       0        0        0     0       0        0
9381       1    0       0       0        0        0     0       0        0

      As  Asafa  Ascot  Ashdown  Ashley  Ashton  Ashwin  Asia  Asian  Asked  \
5903   0      0      0        0       0       0       0     0      0      0
9826   0      0      0        0       0       0       0     0      0      0
8632   0      0      0        0       0       0       0     0      0      0
3138   0      0      0        0       0       0       0     0      0      0
9381   0      0      0        0       0       0       0     0      0      0

      Aspinal  Assad  Assembly  Assistance  Assistant  Assisted  Associated  \
5903        0      0         0           0          0         0           0
9826        0      0         0           0          0         0           0
8632        0      0         0           0          0         0           0
3138        0      0         0           0          0         0           0
9381        0      0         0           0          0         0           0

      Association  Aston  Astronomers  At  Athay  Athens  Athletic  Atkinson  \
5903            0      0            0   0      0       0         0         0
9826            1      0            0   1      0       0         0         0
8632            0      0            0   0      0       0         0         0
3138            0      0            0   0      0       0         0         0
9381            0      1            0   0      0       0         0         0

      Atlanta  Atlantic  Atlantis  Atletico  Attorney  Attorneys  Aubameyang  \
5903        0         0         0         0         0          0           0
9826        0         0         0         0         0          0           0
8632        0         0         0         0         0          0           0
3138        0         0         0         0         0          0           0
9381        0         0         0         0         0          0           0

      Auckland  Auction  August  Aunt  Aurora  Austin  Australia  Australian  \
5903         0        0       0     0       0       0          0           2
9826         0        0       0     0       0       0          0           0
8632         0        0       0     0       0       0          0           0
3138         0        0       0     0       0       0          0           0
9381         0        0       0     0       0       0          0           0

      Austria  Austrian  Authorities  Authority  Autumn  Available  Avengers  \
5903        0         0            0          0       0          0         0
9826        0         0            0          0       0          0         0
8632        1         0            0          0       0          0         0
3138        1         0            0          0       0          0         0
9381        0         0            0          0       0          0         0

      Aviation  Aviv  Award  Awards  Ayatollah  Ayliffe  Aylward  Azamat  \
5903         0     0      0       0          0        0        0       0
9826         0     0      0       0          0        0        0       0
8632         0     0      0       0          0        0        0       0
3138         0     0      0       0          0        0        0       0
9381         0     0      0       0          0        0        0       0

      Azarenka  B  BA  BBC  BC  BFW  BJP  BMI  BMW  BP  BRICS  Babies  Baby  \
5903         0  0   0    0   0    0    0    0    0   0      0       0     0
9826         0  0   0    0   0    0    0    0    0   0      0       0     0
8632         0  0   0    0   0    0    0    0    0   0      0       0     0
3138         0  0   0    0   0    0    0    0    0   0      0       0     0
9381         0  0   0    0   0    0    0    0    0   0      0       0     0

      Baca  Bach  Bachelor  Back  Backstreet  Bad  Baghdad  Bahrain  Bailey  \
5903     0     0         0     0           0    0        0        0       0
9826     0     0         0     0           0    0        0        0       0
8632     0     0         0     0           0    0        0        0       0
3138     0     0         0     0           0    0        0        0       0
9381     0     0         0     0           0    0        0        0       0

      Baines  Bakambu  Baker  Baldwin  Bale  Bali  Ball  Ballmer  Balotelli  \
5903       0        0      0        0     0     0     0        0          0
9826       0        0      0        0     0     0     0        0          0
8632       0        0      0        0     0     0     0        0          0
3138       0        0      0        0     0     0     0        0          0
9381       0        0      0        0     0     0     0        0          0

      Balpa  Baltimore  Band  Bang  Bangerz  Bangkok  Bangladesh  Bank  Banks  \
5903      0          0     0     0        0        0           0     0      0
9826      0          0     0     0        0        0           0     0      0
8632      0          0     0     0        0        0           0     0      0
3138      0          0     0     0        0        0           0     0      0
9381      0          0     0     0        0        0           0     0      0

      Baptist  Barack  Barbara  Barbie  Barcelona  Barlow  Barnard  Barnes  \
5903        0       0        0       0          0       0        0       0
9826        0       0        0       0          0       0        0       0
8632        0       0        0       0          0       0        0       0
3138        0       0        0       0          0       0        0       0
9381        0       0        0       0          0       0        0       0

      Barranco  Barrett  Barry  Bartlett  Base  Based  Basel  Bashar  \
5903         0        0      0         0     0      0      0       0
9826         0        0      0         0     0      0      0       0
8632         0        0      0         0     0      0      0       0
3138         0        0      0         0     0      0      0       0
9381         0        0      0         0     0      0      0       0

      Basically  Basin  Bass  Bastian  Bastille  Bata  Bath  Batman  Battle  \
5903          0      0     0        0         0     0     0       0       0
9826          0      0     0        0         0     0     0       0       0
8632          0      0     0        0         0     0     0       0       0
3138          0      0     0        0         0     0     0       0       0
9381          0      0     0        0         0     0     0       0       0


In [15]:
#| code-summary: 'TF-IDF from Lab 3'
tfidf_vectorizer = TfidfVectorizer(
    tokenizer = spacy_tokenizer,
    token_pattern = None,
    lowercase = False,
    min_df = 2
)
X_train_tfidf = tfidf_vectorizer.fit_transform(df_train_bal['text'])
X_test_tfidf = tfidf_vectorizer.transform(df_test['text'])
print(f'The vocabulary size is {len(tfidf_vectorizer.vocabulary_)} tokens\n')
pd.DataFrame(X_train_tfidf.toarray(), index=df_train_bal.index, columns=tfidf_vectorizer.get_feature_names_out()).head()

The vocabulary size is 15509 tokens

             A  ABC   AC  ACA  ACLU  AFP   AG  AIDS  AIDs   AM  AMIA   AP  \
5903  0.021084  0.0  0.0  0.0   0.0  0.0  0.0   0.0   0.0  0.0   0.0  0.0
9826  0.000000  0.0  0.0  0.0   0.0  0.0  0.0   0.0   0.0  0.0   0.0  0.0
8632  0.020110  0.0  0.0  0.0   0.0  0.0  0.0   0.0   0.0  0.0   0.0  0.0
3138  0.000000  0.0  0.0  0.0   0.0  0.0  0.0   0.0   0.0  0.0   0.0  0.0
9381  0.000000  0.0  0.0  0.0   0.0  0.0  0.0   0.0   0.0  0.0   0.0  0.0

      AQAP  ATM  ATOL  ATP  Aaron  Aasiya  Abaaoud  Abbey  Abdel  Abdelhamid  \
5903   0.0  0.0   0.0  0.0    0.0     0.0      0.0    0.0    0.0         0.0
9826   0.0  0.0   0.0  0.0    0.0     0.0      0.0    0.0    0.0         0.0
8632   0.0  0.0   0.0  0.0    0.0     0.0      0.0    0.0    0.0         0.0
3138   0.0  0.0   0.0  0.0    0.0     0.0      0.0    0.0    0.0         0.0
9381   0.0  0.0   0.0  0.0    0.0     0.0      0.0    0.0    0.0         0.0

      Abdul  AbdulMutallab  Abdulaziz  Abdullah  Abe  Abed  Aberdeen  \
5903    0.0            0.0        0.0       0.0  0.0   0.0       0.0
9826    0.0            0.0        0.0       0.0  0.0   0.0       0.0
8632    0.0            0.0        0.0       0.0  0.0   0.0       0.0
3138    0.0            0.0        0.0       0.0  0.0   0.0       0.0
9381    0.0            0.0        0.0       0.0  0.0   0.0       0.0

      Abhishek  About  Above  Abraham  Abrahams  Abrams      Abu  Abzug  \
5903       0.0    0.0    0.0      0.0       0.0     0.0  0.00000    0.0
9826       0.0    0.0    0.0      0.0       0.0     0.0  0.00000    0.0
8632       0.0    0.0    0.0      0.0       0.0     0.0  0.10975    0.0
3138       0.0    0.0    0.0      0.0       0.0     0.0  0.00000    0.0
9381       0.0    0.0    0.0      0.0       0.0     0.0  0.00000    0.0

      Academy  Accord  According  Accra  Accused  Achieve  Achievement  \
5903      0.0     0.0   0.000000    0.0      0.0      0.0          0.0
9826      0.0     0.0   0.000000    0.0      0.0      0.0          0.0
8632      0.0     0.0   0.000000    0.0      0.0      0.0          0.0
3138      0.0     0.0   0.027964    0.0      0.0      0.0          0.0
9381      0.0     0.0   0.000000    0.0      0.0      0.0          0.0

      Across  Act  Acting  Action  Actions  Active  Activist  Activities  \
5903     0.0  0.0     0.0     0.0      0.0     0.0       0.0         0.0
9826     0.0  0.0     0.0     0.0      0.0     0.0       0.0         0.0
8632     0.0  0.0     0.0     0.0      0.0     0.0       0.0         0.0
3138     0.0  0.0     0.0     0.0      0.0     0.0       0.0         0.0
9381     0.0  0.0     0.0     0.0      0.0     0.0       0.0         0.0

      Actor  Actors  Actress  Actually  Adam  Adding  Additional  \
5903    0.0     0.0      0.0       0.0   0.0     0.0         0.0
9826    0.0     0.0      0.0       0.0   0.0     0.0         0.0
8632    0.0     0.0      0.0       0.0   0.0     0.0         0.0
3138    0.0     0.0      0.0       0.0   0.0     0.0         0.0
9381    0.0     0.0      0.0       0.0   0.0     0.0         0.0

      Additionally  Adele  Adidas  Administration  Administrator  Adolf  \
5903           0.0    0.0     0.0             0.0            0.0    0.0
9826           0.0    0.0     0.0             0.0            0.0    0.0
8632           0.0    0.0     0.0             0.0            0.0    0.0
3138           0.0    0.0     0.0             0.0            0.0    0.0
9381           0.0    0.0     0.0             0.0            0.0    0.0

      Adrian  Advanced  Adventures  Advocates  Affairs  Affleck  Affordable  \
5903     0.0       0.0         0.0        0.0      0.0      0.0         0.0
9826     0.0       0.0         0.0        0.0      0.0      0.0         0.0
8632     0.0       0.0         0.0        0.0      0.0      0.0         0.0
3138     0.0       0.0         0.0        0.0      0.0      0.0         0.0
9381     0.0       0.0         0.0        0.0      0.0      0.0         0.0

      Afghan  Afghanistan  Africa   African     After  Afterwards  Again  \
5903     0.0          0.0     0.0  0.000000  0.000000         0.0    0.0
9826     0.0          0.0     0.0  0.000000  0.030048         0.0    0.0
8632     0.0          0.0     0.0  0.041967  0.000000         0.0    0.0
3138     0.0          0.0     0.0  0.000000  0.000000         0.0    0.0
9381     0.0          0.0     0.0  0.000000  0.000000         0.0    0.0

      Against  Agatha  Age  Agency  Agent  Agree  Agriculture   Ah  Ahlers  \
5903      0.0     0.0  0.0     0.0    0.0    0.0          0.0  0.0     0.0
9826      0.0     0.0  0.0     0.0    0.0    0.0          0.0  0.0     0.0
8632      0.0     0.0  0.0     0.0    0.0    0.0          0.0  0.0     0.0
3138      0.0     0.0  0.0     0.0    0.0    0.0          0.0  0.0     0.0
9381      0.0     0.0  0.0     0.0    0.0    0.0          0.0  0.0     0.0

      Ahmed  Aid  Air  AirAsia  Airbus  Aires  Airline  Airlines  Airplane  \
5903    0.0  0.0  0.0      0.0     0.0    0.0      0.0       0.0       0.0
9826    0.0  0.0  0.0      0.0     0.0    0.0      0.0       0.0       0.0
8632    0.0  0.0  0.0      0.0     0.0    0.0      0.0       0.0       0.0
3138    0.0  0.0  0.0      0.0     0.0    0.0      0.0       0.0       0.0
9381    0.0  0.0  0.0      0.0     0.0    0.0      0.0       0.0       0.0

      Airport  Airways  Akaichi  Akka   Al  Alabama  Alain  Alamuddin  Alan  \
5903      0.0      0.0      0.0   0.0  0.0      0.0    0.0        0.0   0.0
9826      0.0      0.0      0.0   0.0  0.0      0.0    0.0        0.0   0.0
8632      0.0      0.0      0.0   0.0  0.0      0.0    0.0        0.0   0.0
3138      0.0      0.0      0.0   0.0  0.0      0.0    0.0        0.0   0.0
9381      0.0      0.0      0.0   0.0  0.0      0.0    0.0        0.0   0.0

      Alaska  Alaskan  Alba  Albert  Alberto  Albie  Album  Alcohol  Alec  \
5903     0.0      0.0   0.0     0.0      0.0    0.0    0.0      0.0   0.0
9826     0.0      0.0   0.0     0.0      0.0    0.0    0.0      0.0   0.0
8632     0.0      0.0   0.0     0.0      0.0    0.0    0.0      0.0   0.0
3138     0.0      0.0   0.0     0.0      0.0    0.0    0.0      0.0   0.0
9381     0.0      0.0   0.0     0.0      0.0    0.0    0.0      0.0   0.0

      Alejandro  Aleppo  Alert  Alex  Alexa  Alexander  Alexandre  Alexandria  \
5903        0.0     0.0    0.0   0.0    0.0   0.000000        0.0         0.0
9826        0.0     0.0    0.0   0.0    0.0   0.000000        0.0         0.0
8632        0.0     0.0    0.0   0.0    0.0   0.052197        0.0         0.0
3138        0.0     0.0    0.0   0.0    0.0   0.000000        0.0         0.0
9381        0.0     0.0    0.0   0.0    0.0   0.000000        0.0         0.0

        Alexis  Alfie  Algeria  Ali  Alice  Alison  Alito  Alive  All  \
5903  0.000000    0.0      0.0  0.0    0.0     0.0    0.0    0.0  0.0
9826  0.000000    0.0      0.0  0.0    0.0     0.0    0.0    0.0  0.0
8632  0.000000    0.0      0.0  0.0    0.0     0.0    0.0    0.0  0.0
3138  0.000000    0.0      0.0  0.0    0.0     0.0    0.0    0.0  0.0
9381  0.070882    0.0      0.0  0.0    0.0     0.0    0.0    0.0  0.0

      Allegations  Allen  Alliance  Allred  Almost  Along  Alongside  Alonso  \
5903     0.000000    0.0       0.0     0.0     0.0    0.0        0.0     0.0
9826     0.000000    0.0       0.0     0.0     0.0    0.0        0.0     0.0
8632     0.000000    0.0       0.0     0.0     0.0    0.0        0.0     0.0
3138     0.062178    0.0       0.0     0.0     0.0    0.0        0.0     0.0
9381     0.000000    0.0       0.0     0.0     0.0    0.0        0.0     0.0

      Alpine  Also  Alternatives  Although  Always  Alzheimer  Amal  Amanda  \
5903     0.0   0.0           0.0       0.0     0.0        0.0   0.0     0.0
9826     0.0   0.0           0.0       0.0     0.0        0.0   0.0     0.0
8632     0.0   0.0           0.0       0.0     0.0        0.0   0.0     0.0
3138     0.0   0.0           0.0       0.0     0.0        0.0   0.0     0.0
9381     0.0   0.0           0.0       0.0     0.0        0.0   0.0     0.0

      Amazon  Amber  Ambrose  Amedy  Amelia  Amendment  America  American  \
5903     0.0    0.0      0.0    0.0     0.0        0.0      0.0  0.032369
9826     0.0    0.0      0.0    0.0     0.0        0.0      0.0  0.026335
8632     0.0    0.0      0.0    0.0     0.0        0.0      0.0  0.000000
3138     0.0    0.0      0.0    0.0     0.0        0.0      0.0  0.093904
9381     0.0    0.0      0.0    0.0     0.0        0.0      0.0  0.000000

      Americans  Americas  Amid  Amidst     Among  Amphipolis  Amsterdam  Amy  \
5903   0.000000       0.0   0.0     0.0  0.000000         0.0        0.0  0.0
9826   0.000000       0.0   0.0     0.0  0.000000         0.0        0.0  0.0
8632   0.000000       0.0   0.0     0.0  0.000000         0.0        0.0  0.0
3138   0.121325       0.0   0.0     0.0  0.046376         0.0        0.0  0.0
9381   0.000000       0.0   0.0     0.0  0.000000         0.0        0.0  0.0

            An  Ana  Anadappa  Analysis  Analysts  Analytics  Anchorage  And  \
5903  0.000000  0.0       0.0       0.0       0.0        0.0        0.0  0.0
9826  0.000000  0.0       0.0       0.0       0.0        0.0        0.0  0.0
8632  0.000000  0.0       0.0       0.0       0.0        0.0        0.0  0.0
3138  0.038852  0.0       0.0       0.0       0.0        0.0        0.0  0.0
9381  0.000000  0.0       0.0       0.0       0.0        0.0        0.0  0.0

      Anderlecht  Anders  Andersen  Anderson  Andre  Andrea  Andrew  Android  \
5903         0.0     0.0       0.0       0.0    0.0     0.0     0.0      0.0
9826         0.0     0.0       0.0       0.0    0.0     0.0     0.0      0.0
8632         0.0     0.0       0.0       0.0    0.0     0.0     0.0      0.0
3138         0.0     0.0       0.0       0.0    0.0     0.0     0.0      0.0
9381         0.0     0.0       0.0       0.0    0.0     0.0     0.0      0.0

          Andy  Anfield  Angel  Angela  Angeles  Angelina  Angry  Angus  \
5903  0.000000      0.0    0.0     0.0      0.0       0.0    0.0    0.0
9826  0.000000      0.0    0.0     0.0      0.0       0.0    0.0    0.0
8632  0.049665      0.0    0.0     0.0      0.0       0.0    0.0    0.0
3138  0.000000      0.0    0.0     0.0      0.0       0.0    0.0    0.0
9381  0.000000      0.0    0.0     0.0      0.0       0.0    0.0    0.0

      Animal  Aniston  Ankara       Ann  Anna  Annapolis  Anne  Annie  \
5903     0.0      0.0     0.0  0.066079   0.0        0.0   0.0    0.0
9826     0.0      0.0     0.0  0.000000   0.0        0.0   0.0    0.0
8632     0.0      0.0     0.0  0.000000   0.0        0.0   0.0    0.0
3138     0.0      0.0     0.0  0.000000   0.0        0.0   0.0    0.0
9381     0.0      0.0     0.0  0.000000   0.0        0.0   0.0    0.0

      Announces  Annual   Another  Antarctic  Anthony  Anti  Antoine  Antonio  \
5903        0.0     0.0  0.044415        0.0      0.0   0.0      0.0      0.0
9826        0.0     0.0  0.000000        0.0      0.0   0.0      0.0      0.0
8632        0.0     0.0  0.000000        0.0      0.0   0.0      0.0      0.0
3138        0.0     0.0  0.000000        0.0      0.0   0.0      0.0      0.0
9381        0.0     0.0  0.000000        0.0      0.0   0.0      0.0      0.0

      Any  Anybody  Anyone  Anytime  Apollo  App  Apparel  Apparently  \
5903  0.0      0.0     0.0      0.0     0.0  0.0      0.0         0.0
9826  0.0      0.0     0.0      0.0     0.0  0.0      0.0         0.0
8632  0.0      0.0     0.0      0.0     0.0  0.0      0.0         0.0
3138  0.0      0.0     0.0      0.0     0.0  0.0      0.0         0.0
9381  0.0      0.0     0.0      0.0     0.0  0.0      0.0         0.0

      Appeals  Apple  Applied  Apps     April  Apsley  Arab  Arabia  Arabian  \
5903      0.0    0.0      0.0   0.0  0.000000     0.0   0.0     0.0      0.0
9826      0.0    0.0      0.0   0.0  0.000000     0.0   0.0     0.0      0.0
8632      0.0    0.0      0.0   0.0  0.000000     0.0   0.0     0.0      0.0
3138      0.0    0.0      0.0   0.0  0.041263     0.0   0.0     0.0      0.0
9381      0.0    0.0      0.0   0.0  0.000000     0.0   0.0     0.0      0.0

      Arch  Archaeologists  Archer  Archives  Arctic  Are  Aren  Arena  \
5903   0.0             0.0     0.0       0.0     0.0  0.0   0.0    0.0
9826   0.0             0.0     0.0       0.0     0.0  0.0   0.0    0.0
8632   0.0             0.0     0.0       0.0     0.0  0.0   0.0    0.0
3138   0.0             0.0     0.0       0.0     0.0  0.0   0.0    0.0
9381   0.0             0.0     0.0       0.0     0.0  0.0   0.0    0.0

      Argentina  Argentine  Argo  Arizona  Arkansas  Arlington  Armed  Army  \
5903        0.0        0.0   0.0      0.0       0.0        0.0    0.0   0.0
9826        0.0        0.0   0.0      0.0       0.0        0.0    0.0   0.0
8632        0.0        0.0   0.0      0.0       0.0        0.0    0.0   0.0
3138        0.0        0.0   0.0      0.0       0.0        0.0    0.0   0.0
9381        0.0        0.0   0.0      0.0       0.0        0.0    0.0   0.0

      Arnold  Around  Arpaio  Arquette  Arrest  Arrested  Arsenal   Arsene  \
5903     0.0     0.0     0.0       0.0     0.0       0.0   0.0000  0.00000
9826     0.0     0.0     0.0       0.0     0.0       0.0   0.0000  0.00000
8632     0.0     0.0     0.0       0.0     0.0       0.0   0.0000  0.00000
3138     0.0     0.0     0.0       0.0     0.0       0.0   0.0000  0.00000
9381     0.0     0.0     0.0       0.0     0.0       0.0   0.3274  0.06862

      Art  Arteta  Arthur  Article  Artists  Arts  Arturo  Artwalk   As  \
5903  0.0     0.0     0.0      0.0      0.0   0.0     0.0      0.0  0.0
9826  0.0     0.0     0.0      0.0      0.0   0.0     0.0      0.0  0.0
8632  0.0     0.0     0.0      0.0      0.0   0.0     0.0      0.0  0.0
3138  0.0     0.0     0.0      0.0      0.0   0.0     0.0      0.0  0.0
9381  0.0     0.0     0.0      0.0      0.0   0.0     0.0      0.0  0.0

      Asafa  Ascot  Ashdown  Ashley  Ashton  Ashwin  Asia  Asian  Asked  \
5903    0.0    0.0      0.0     0.0     0.0     0.0   0.0    0.0    0.0
9826    0.0    0.0      0.0     0.0     0.0     0.0   0.0    0.0    0.0
8632    0.0    0.0      0.0     0.0     0.0     0.0   0.0    0.0    0.0
3138    0.0    0.0      0.0     0.0     0.0     0.0   0.0    0.0    0.0
9381    0.0    0.0      0.0     0.0     0.0     0.0   0.0    0.0    0.0

      Aspinal  Assad  Assembly  Assistance  Assistant  Assisted  Associated  \
5903      0.0    0.0       0.0         0.0        0.0       0.0         0.0
9826      0.0    0.0       0.0         0.0        0.0       0.0         0.0
8632      0.0    0.0       0.0         0.0        0.0       0.0         0.0
3138      0.0    0.0       0.0         0.0        0.0       0.0         0.0
9381      0.0    0.0       0.0         0.0        0.0       0.0         0.0

      Association    Aston  Astronomers        At  Athay  Athens  Athletic  \
5903     0.000000  0.00000          0.0  0.000000    0.0     0.0       0.0
9826     0.037865  0.00000          0.0  0.028586    0.0     0.0       0.0
8632     0.000000  0.00000          0.0  0.000000    0.0     0.0       0.0
3138     0.000000  0.00000          0.0  0.000000    0.0     0.0       0.0
9381     0.000000  0.06862          0.0  0.000000    0.0     0.0       0.0

      Atkinson  Atlanta  Atlantic  Atlantis  Atletico  Attorney  Attorneys  \
5903       0.0      0.0       0.0       0.0       0.0       0.0        0.0
9826       0.0      0.0       0.0       0.0       0.0       0.0        0.0
8632       0.0      0.0       0.0       0.0       0.0       0.0        0.0
3138       0.0      0.0       0.0       0.0       0.0       0.0        0.0
9381       0.0      0.0       0.0       0.0       0.0       0.0        0.0

      Aubameyang  Auckland  Auction  August  Aunt  Aurora  Austin  Australia  \
5903         0.0       0.0      0.0     0.0   0.0     0.0     0.0        0.0
9826         0.0       0.0      0.0     0.0   0.0     0.0     0.0        0.0
8632         0.0       0.0      0.0     0.0   0.0     0.0     0.0        0.0
3138         0.0       0.0      0.0     0.0   0.0     0.0     0.0        0.0
9381         0.0       0.0      0.0     0.0   0.0     0.0     0.0        0.0

      Australian   Austria  Austrian  Authorities  Authority  Autumn  \
5903    0.097837  0.000000       0.0          0.0        0.0     0.0
9826    0.000000  0.000000       0.0          0.0        0.0     0.0
8632    0.000000  0.058651       0.0          0.0        0.0     0.0
3138    0.000000  0.059462       0.0          0.0        0.0     0.0
9381    0.000000  0.000000       0.0          0.0        0.0     0.0

      Available  Avengers  Aviation  Aviv  Award  Awards  Ayatollah  Ayliffe  \
5903        0.0       0.0       0.0   0.0    0.0     0.0        0.0      0.0
9826        0.0       0.0       0.0   0.0    0.0     0.0        0.0      0.0
8632        0.0       0.0       0.0   0.0    0.0     0.0        0.0      0.0
3138        0.0       0.0       0.0   0.0    0.0     0.0        0.0      0.0
9381        0.0       0.0       0.0   0.0    0.0     0.0        0.0      0.0

      Aylward  Azamat  Azarenka    B   BA  BBC   BC  BFW  BJP  BMI  BMW   BP  \
5903      0.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9826      0.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8632      0.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3138      0.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9381      0.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

      BRICS  Babies  Baby  Baca  Bach  Bachelor  Back  Backstreet  Bad  \
5903    0.0     0.0   0.0   0.0   0.0       0.0   0.0         0.0  0.0
9826    0.0     0.0   0.0   0.0   0.0       0.0   0.0         0.0  0.0
8632    0.0     0.0   0.0   0.0   0.0       0.0   0.0         0.0  0.0
3138    0.0     0.0   0.0   0.0   0.0       0.0   0.0         0.0  0.0
9381    0.0     0.0   0.0   0.0   0.0       0.0   0.0         0.0  0.0

      Baghdad  Bahrain  Bailey  Baines  Bakambu  Baker  Baldwin  Bale  Bali  \
5903      0.0      0.0     0.0     0.0      0.0    0.0      0.0   0.0   0.0
9826      0.0      0.0     0.0     0.0      0.0    0.0      0.0   0.0   0.0
8632      0.0      0.0     0.0     0.0      0.0    0.0      0.0   0.0   0.0
3138      0.0      0.0     0.0     0.0      0.0    0.0      0.0   0.0   0.0
9381      0.0      0.0     0.0     0.0      0.0    0.0      0.0   0.0   0.0

      Ball  Ballmer  Balotelli  Balpa  Baltimore  Band  Bang  Bangerz  \
5903   0.0      0.0        0.0    0.0        0.0   0.0   0.0      0.0
9826   0.0      0.0        0.0    0.0        0.0   0.0   0.0      0.0
8632   0.0      0.0        0.0    0.0        0.0   0.0   0.0      0.0
3138   0.0      0.0        0.0    0.0        0.0   0.0   0.0      0.0
9381   0.0      0.0        0.0    0.0        0.0   0.0   0.0      0.0

      Bangkok  Bangladesh  Bank  Banks  Baptist  Barack  Barbara  Barbie  \
5903      0.0         0.0   0.0    0.0      0.0     0.0      0.0     0.0
9826      0.0         0.0   0.0    0.0      0.0     0.0      0.0     0.0
8632      0.0         0.0   0.0    0.0      0.0     0.0      0.0     0.0
3138      0.0         0.0   0.0    0.0      0.0     0.0      0.0     0.0
9381      0.0         0.0   0.0    0.0      0.0     0.0      0.0     0.0

      Barcelona  Barlow  Barnard  Barnes  Barranco  Barrett  Barry  Bartlett  \
5903        0.0     0.0      0.0     0.0       0.0      0.0    0.0       0.0
9826        0.0     0.0      0.0     0.0       0.0      0.0    0.0       0.0
8632        0.0     0.0      0.0     0.0       0.0      0.0    0.0       0.0
3138        0.0     0.0      0.0     0.0       0.0      0.0    0.0       0.0
9381        0.0     0.0      0.0     0.0       0.0      0.0    0.0       0.0

      Base  Based  Basel  Bashar  Basically  Basin  Bass  Bastian  Bastille  \
5903   0.0    0.0    0.0     0.0        0.0    0.0   0.0      0.0       0.0
9826   0.0    0.0    0.0     0.0        0.0    0.0   0.0      0.0       0.0

## Embeddings

In [16]:
#| code-summary: 'Word2Vec from Lab 4'
# Download to FILE (1662.8MB, ~30 minutes) once (else just returns downloaded file path)
wv_path = api.load('word2vec-google-news-300', return_path=True)

# Load vectors into RAM (limit if needed)
limit = 1000000
wv_vectors = KeyedVectors.load_word2vec_format(wv_path, binary=True, limit=limit)
print(f'Loaded KeyedVectors with {len(wv_vectors)} vectors in {wv_vectors.vector_size} dimensions')

#| code-summary: 'Generate mean embedding vectors for each document'
X_train_mean_wv = np.vstack([wv_vectors.get_mean_vector(spacy_tokenizer(doc)).reshape(1, -1) for doc in df_train_bal['text']])
X_test_mean_wv = np.vstack([wv_vectors.get_mean_vector(spacy_tokenizer(doc)).reshape(1, -1) for doc in df_test['text']])

pd.DataFrame(X_train_mean_wv, index=df_train_bal.index).head()

Loaded KeyedVectors with 1000000 vectors in 300 dimensions

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299
5903,0.014426,0.014005,0.021852,0.018497,0.005867,-0.033191,0.002082,-0.042596,0.032506,0.045204,-0.019508,-0.026656,0.006145,0.021831,-0.034212,0.003694,0.023187,0.023144,0.007048,-0.012668,-0.009819,0.026328,-0.017451,-0.011728,0.027078,-0.011569,-0.031783,0.028818,0.016716,0.018335,-0.005151,-0.009505,-0.019306,-0.016954,0.003485,-0.005387,-0.014614,-0.011707,0.010326,0.026830,0.032739,-0.031915,0.038083,-0.009990,-0.000510,-0.005135,-0.007729,0.004062,0.027145,0.032266,0.006575,0.031737,0.003735,-0.010632,-0.027775,0.019339,-0.018524,-0.023141,0.010547,-0.026340,-0.029262,0.016730,-0.030493,-0.063066,-0.022877,0.014589,0.015547,0.028707,0.002786,0.044673,0.013731,-0.010875,0.023319,0.017266,-0.042808,-0.026057,0.029462,0.035110,0.008527,0.036385,-0.000799,-0.040883,0.017831,-0.001171,-0.006067,-0.025726,-0.045084,0.038697,-0.011285,0.000181,0.017849,0.012940,-0.017890,-0.038520,-0.018079,-0.027136,0.011116,-0.008501,-0.027135,0.007881,-0.015753,-0.022809,0.003651,-0.004814,-0.011045,-0.022476,-0.004201,-0.014369,-0.007125,-0.012333,0.008390,-0.002848,-0.009220,-0.009538,0.019483,0.012655,0.026784,0.003458,0.043459,0.027280,-0.052663,-0.001955,-0.016958,0.019783,-0.015575,-0.010773,-0.006793,-0.030684,-0.000763,0.027090,-0.002932,-0.035439,-0.046033,-0.012338,-0.024280,-0.029154,-0.002016,-0.008153,-0.041501,0.023872,0.004038,-0.019929,0.013944,-0.008200,-0.001767,0.030989,-0.012965,-0.022980,-0.029732,0.011730,0.025282,0.014849,-0.026816,0.024361,-0.005660,0.007743,-0.025615,-0.039668,0.001939,-0.014001,-0.022481,0.012005,0.035328,-0.000661,-0.000856,-0.014095,0.025760,-0.008741,0.019454,-0.021059,-0.041087,-0.022813,-0.009596,-0.043330,-0.015533,-0.024522,0.026225,-0.023367,-0.008395,-0.000957,-0.028829,-0.011278,0.000771,0.016053,-0.010349,-0.010768,0.000413,0.013922,0.040837,0.010545,0.010650,-0.003660,0.032277,0.000150,-0.035601,0.019612,0.002364,-0.009782,-0.034149,-0.057675,0.005675,0.012421,-0.006379,-0.001628,0.012040,-0.020268,-0.008528,0.008049,0.008391,-0.018101,-0.009277,0.018175,-0.002994,0.022613,-0.030794,-0.011841,0.027227,-0.019903,-0.055413,-0.010177,0.002210,0.007418,0.012068,-0.027701,0.015725,-0.016505,0.015181,0.013134,0.030976,0.002264,0.001727,-0.023431,0.010055,0.011977,0.008935,-0.001876,0.005330,-0.021825,0.020017,0.021050,0.014117,-0.001838,0.022684,-0.057890,0.003604,0.002881,0.008408,0.017160,0.015179,-0.005272,0.011676,0.004261,0.007951,0.007667,0.011389,0.003355,0.031649,0.004641,-0.023600,-0.019856,0.004509,0.024860,-0.008525,0.022403,0.042191,0.038352,0.011422,0.019658,-0.010986,0.000524,0.017612,0.026855,0.009606,0.004861,0.040389,-0.030201,-0.022472,-0.049524,-0.001976,-0.010071,0.020109,-0.014247,-0.005037,0.030724,0.003610,0.003678,-0.041286,0.003178,-0.008369,0.021877,-0.022679,-0.002873,-0.044184,0.002238,-0.019691,-0.003303,-0.008211,-0.013183,0.016145,-0.019254
9826,0.000289,0.020248,0.014810,0.038037,-0.021074,-0.005111,0.016268,-0.038335,0.039617,0.022282,-0.031798,-0.048521,-0.003450,0.029213,-0.033757,0.018514,0.010924,0.034108,-0.007290,-0.009761,-0.010313,0.002508,-0.019366,0.002276,0.011549,-0.007441,-0.047279,0.032161,-0.004638,0.005878,-0.002748,-0.011619,-0.013859,-0.006501,-0.005370,-0.001324,-0.012978,-0.013778,0.012337,0.014038,0.033429,-0.012953,0.004038,-0.006677,0.000618,-0.020518,-0.004340,0.014262,-0.008677,0.009313,0.006889,0.009697,-0.016708,-0.018328,-0.001977,0.015085,-0.022280,-0.017229,0.010621,-0.010348,-0.030248,0.040041,-0.030466,-0.041740,-0.007213,0.007560,-0.004444,0.041865,-0.001061,0.023581,0.003928,-0.009566,0.037947,0.012723,-0.030503,-0.028480,0.036121,0.035728,0.019357,0.068259,0.007522,-0.044107,0.009431,0.008823,-0.023741,-0.030495,-0.044400,0.032628,-0.003743,-0.009330,0.025654,0.005336,-0.007209,-0.038245,-0.007440,-0.013220,0.024654,-0.003721,0.006080,0.018923,0.013890,-0.041472,0.000227,-0.005120,-0.004682,-0.017798,-0.014094,-0.017821,0.023521,-0.032603,-0.003749,0.005672,-0.013282,-0.001080,0.026641,0.007787,0.015392,-0.008925,0.050558,0.030608,-0.057380,0.000015,-0.032923,0.004387,-0.005285,-0.011031,-0.006868,-0.021753,0.015463,0.030903,0.004777,-0.039423,-0.047060,-0.023135,-0.015846,-0.041722,0.006428,-0.008406,-0.012142,0.037406,0.012441,-0.013538,0.007556,0.009898,0.014931,-0.007000,0.000332,-0.029223,-0.040576,0.005076,0.021252,-0.001628,-0.029525,0.020044,0.007705,-0.009585,-0.023280,-0.034231,-0.008562,-0.017799,0.000490,0.032832,0.022585,0.015103,-0.008998,-0.015054,0.011936,0.000112,0.003790,-0.029922,-0.038748,-0.023707,-0.024143,-0.034564,-0.003982,-0.027172,0.017862,-0.030897,-0.004313,0.001851,-0.020040,-0.020756,-0.005025,0.003757,-0.004500,-0.001210,-0.007771,0.010968,0.044350,0.023497,-0.001580,-0.010783,0.006436,-0.011815,-0.037775,0.008112,0.002395,-0.005771,-0.015326,-0.060634,0.006549,0.012419,0.000956,0.005607,-0.001442,-0.012601,-0.009183,-0.001291,0.024196,-0.018172,-0.011383,-0.000998,-0.013787,0.031014,-0.031311,0.005810,0.028920,-0.004818,-0.035819,0.004669,-0.001381,0.009207,0.014394,-0.016523,0.036322,-0.016158,0.002385,0.000092,0.012874,0.013655,0.012714,-0.013430,0.026136,0.009960,-0.003986,-0.023986,0.004882,-0.008468,0.020557,-0.004031,0.011870,-0.016770,0.019316,-0.045178,0.016557,-0.000487,0.019848,0.032682,-0.002315,-0.011272,0.017558,-0.013075,0.019392,0.007746,0.016585,-0.005560,0.017677,0.007579,-0.022355,-0.008023,0.007545,-0.003382,-0.025219,0.023466,0.022180,0.041360,-0.008396,-0.002277,-0.012208,-0.001849,0.024232,0.033366,0.028513,0.010478,0.027520,-0.028815,-0.030545,-0.033953,-0.007282,-0.019235,0.018488,0.002995,0.005339,0.027012,0.003494,-0.003890,-0.019318,-0.000238,0.010180,0.004894,-0.026806,-0.006514,-0.030622,0.010849,-0.005334,0.016568,-0.015953,0.005172,0.032575,-0.012083
8632,0.018328,0.022288,0.016098,0.015788,0.006690,-0.033753,-0.006499,-0.043558,0.048635,0.039375,-0.017689,-0.040811,-0.008067,0.009713,-0.041062,0.010857,0.034642,0.026994,0.011524,-0.013886,-0.016460,0.031907,-0.001619,-0.008057,0.026186,-0.014048,-0.045966,0.018265,0.012303,0.014198,0.000257,0.001935,-0.003112,-0.005092,0.013172,0.003589,-0.006433,-0.008798,0.014055,0.025624,0.043601,-0.027255,0.045842,0.008343,0.004465,0.003477,-0.000577,0.004312,0.025685,0.024226,0.004879,0.025683,-0.004190,-0.007551,-0.013717,0.021620,-0.012335,-0.022923,0.013435,-0.033496,-0.023624,0.033665,-0.029543,-0.051726,-0.023457,0.006832,0.008223,0.031090,-0.004021,0.047012,0.017827,-0.010497,0.044439,0.025001,-0.034435,-0.020232,0.034886,0.023226,0.018364,0.032540,0.007660,-0.040867,0.010843,-0.009543,-0.001544,-0.029867,-0.034447,0.036086,-0.007708,0.007910,0.016113,0.026322,-0.022837,-0.041924,-0.026904,-0.032382,0.009859,-0.001510,-0.014697,-0.005542,-0.014617,-0.020855,-0.002344,0.000312,-0.012298,-0.012374,0.005153,-0.021100,-0.006102,-0.023293,0.003068,0.005186,-0.009845,-0.004543,0.020814,-0.004742,0.016600,-0.000500,0.046754,0.024542,-0.054174,-0.000085,-0.019382,0.026572,-0.025015,-0.021818,-0.005707,-0.031409,-0.005239,0.021027,-0.009941,-0.036136,-0.039890,-0.013613,-0.022856,-0.034474,0.006681,0.011544,-0.025677,0.034675,0.010658,-0.020527,0.018997,-0.013931,0.004255,0.031746,-0.022668,-0.032599,-0.030727,0.012367,0.018266,0.023987,-0.024763,0.017988,-0.001583,0.011943,-0.018751,-0.047106,-0.005036,-0.010781,-0.013821,0.016067,0.038366,0.011610,0.003034,-0.021504,0.026196,-0.016803,0.011954,-0.015784,-0.036872,-0.011350,-0.012546,-0.045358,-0.025194,-0.015575,0.028423,-0.033241,0.000292,-0.009254,-0.027856,-0.013829,0.005713,0.022255,-0.015029,-0.001373,-0.001349,0.014769,0.040552,0.003792,0.011808,0.003489,0.013769,-0.001252,-0.031839,0.009016,0.000329,0.007761,-0.024975,-0.057512,0.009077,0.012416,0.008495,0.003239,0.023770,-0.017656,-0.006550,0.003416,0.021245,-0.018193,-0.005114,0.001966,-0.002776,0.031699,-0.037664,-0.002853,0.024185,-0.013028,-0.044473,-0.010623,-0.001391,0.008064,0.009584,-0.015912,0.027016,-0.026206,0.011284,0.007748,0.017287,-0.013046,0.004684,-0.022658,0.007592,0.008268,0.015556,-0.003451,-0.003998,-0.013853,0.025955,-0.006763,0.006336,0.002145,0.017325,-0.053651,0.004745,-0.004951,0.011862,0.011217,0.007958,-0.006619,0.009824,0.003267,0.008355,0.010701,0.014031,0.002578,0.025173,-0.002247,-0.035973,-0.028720,0.011062,0.026193,-0.012022,0.010176,0.052835,0.053771,-0.002992,-0.003204,-0.010053,0.001910,0.024826,0.018056,0.025082,0.007328,0.022831,-0.017355,-0.020061,-0.054467,-0.008655,-0.014876,0.019716,-0.015364,-0.003636,0.038388,0.006839,0.002830,-0.036316,0.004035,0.000487,0.016100,-0.022547,0.004328,-0.037892,0.012108,-0.017557,0.005272,-0.000487,-0.015482,0.011190,-0.023763
3138,0.028308,0.017318,0.021590,0.022334,-0.022442,-0.021089,0.003737,-0.041188,0.047661,0.034118,-0.021618,-0.039426,-0.002318,0.023169,-0.033806,0.012749,0.018013,0.024335,-0.011711,-0.009303,0.006097,0.021677,-0.003077,-0.017967,0.022345,-0.008787,-0.042838,0.031374,0.011436,0.015855,0.000941,-0.011889,-0.019288,0.002795,0.020594,-0.007942,-0.002370,0.001409,0.010200,0.034545,0.029579,-0.012660,0.013959,0.004210,-0.003118,-0.005533,-0.002319,0.008345,0.000885,0.020603,0.015331,0.014019,-0.011843,-0.013414,-0.007926,0.025606,-0.032300,-0.025648,0.006989,-0.027472,-0.014825,0.044597,-0.031561,-0.032570,0.000237,-0.000274,-0.011197,0.030095,0.005911,0.031656,0.004278,0.007503,0.024436,0.033321,-0.018650,-0.012418,0.039256,0.041412,0.021104,0.051229,0.010624,-0.041205,0.015871,0.013171,-0.025073,-0.041980,-0.046973,0.027255,-0.000805,0.002353,0.023695,0.013401,-0.019776,-0.035895,-0.001568,-0.019945,0.016472,-0.001048,0.006184,-0.003068,0.004556,-0.027828,0.002629,0.001688,-0.005375,-0.021741,-0.016153,-0.026927,0.003130,-0.034950,-0.003457,0.007521,-0.016541,-0.002151,0.009333,0.010865,0.027804,-0.000877,0.065516,0.053987,-0.057725,0.002812,-0.040032,0.006024,-0.031804,-0.021117,-0.002205,-0.030342,0.001962,0.014477,-0.015694,-0.038632,-0.040110,-0.025589,-0.003746,-0.030786,0.003989,-0.001185,-0.001528,0.012791,0.009061,-0.012404,-0.000002,0.009938,0.004662,0.000302,0.009262,-0.031713,-0.029330,0.016087,0.043957,-0.003247,-0.029269,0.016576,0.006548,-0.001368,-0.018908,-0.025239,0.007462,-0.000232,-0.002922,0.022032,0.021465,0.014098,-0.001977,0.006800,0.018916,0.004855,0.019146,-0.012327,-0.039570,-0.020628,-0.009594,-0.044865,-0.005325,-0.010385,0.005873,-0.017616,-0.005178,-0.013032,-0.037416,-0.016947,-0.006349,-0.008127,0.003534,-0.007673,-0.011809,0.007245,0.034438,0.029457,0.020909,-0.004745,0.008623,0.006358,-0.045792,0.015486,0.000891,0.003259,-0.016214,-0.056107,0.003877,0.025535,-0.011307,-0.006164,0.016536,-0.004097,0.002658,0.006967,0.018440,-0.017051,-0.012723,-0.004167,-0.001031,0.008529,-0.043824,0.000998,0.020253,0.007869,-0.018019,0.002016,0.001905,-0.000307,0.005013,-0.021126,0.028875,-0.024987,0.016048,0.014728,0.027289,0.002253,0.001671,-0.025129,0.013847,0.017365,0.004558,-0.019582,0.009060,-0.020046,0.016899,-0.006381,0.008581,-0.006562,0.018688,-0.037000,-0.002207,0.000689,0.004815,0.025187,0.007854,-0.013278,0.011173,-0.001078,0.017226,0.008146,0.021639,-0.014750,0.033668,-0.000165,0.000656,-0.014833,0.012001,0.003441,-0.008032,0.031441,0.031512,0.057375,-0.012435,0.005026,-0.002384,0.007461,0.027996,0.034716,0.014944,-0.003389,0.020228,-0.025409,-0.014938,-0.042945,0.000045,-0.016033,-0.001029,0.007957,0.008251,0.046398,0.006052,-0.002839,-0.029193,-0.000732,-0.004785,0.018951,-0.019360,-0.011331,-0.032387,0.016908,-0.009546,0.007594,-0.012340,-0.013545,0.022169,-0.012290
9381,0.018136,0.022931,0.021029,0.021129,-0.000807,-0.025284,-0.003769,-0.051794,0.031729,0.046975,-0.026819,-0.028036,-0.004502,0.017129,-0.031778,0.011938,0.025676,0.027410,0.005412,-0.005165,-0.005609,0.027947,-0.012477,-0.006154,0.026898,0.002368,-0.020093,0.018189,0.014853,0.024970,-0.005504,0.003101,-0.006069,-0.008598,0.010325,0.010446,-0.016262,-0.014632,0.013342,0.028258,0.031311,-0.019015,0.030439,0.004248,0.009168,-0.009446,0.010602,0.011751,0.018963,0.026893,0.002075,0.026466,-0.018378,-0.013695,-0.026494,0.012208,-0.009592,-0.014183,0.001504,-0.030696,-0.038755,0.030285,-0.041873,-0.046874,-0.024129,-0.005682,0.009830,0.032615,0.009202,0.049129,0.017156,-0.002107,0.030925,0.011671,-0.032694,-0.020967,0.035495,0.023982,0.007401,0.034292,0.000931,-0.049141,0.014459,-0.005187,0.012623,-0.035884,-0.028861,0.036675,-0.000694,0.006437,0.019453,0.004874,-0.032804,-0.048783,-0.022448,-0.034415,0.005392,-0.009050,-0.009544,0.009557,-0.003856,-0.029537,0.004366,0.018055,-0.004578,-0.014783,0.000028,-0.034858,0.002136,-0.029717,0.003514,0.015362,-0.003759,-0.021968,0.012760,0.000909,0.021580,0.006857,0.063654,0.030297,-0.036370,-0.015709,-0.040721,0.022145,-0.033249,-0.019376,-0.020001,-0.026301,-0.009829,0.018042,-0.001978,-0.038341,-0.040644,-0.042728,-0.005373,-0.040104,0.001715,0.005071,-0.024994,0.039898,0.015155,-0.017460,0.022761,-0.005952,0.010378,0.034765,-0.020878,-0.021464,-0.032619,0.005322,0.022287,0.022689,-0.024905,0.016096,0.009999,0.002778,-0.018549,-0.041468,0.009826,-0.007135,0.015835,0.016113,0.023972,0.010105,0.008488,-0.019821,0.019630,-0.005875,0.012280,-0.003697,-0.057319,-0.021455,-0.015064,-0.047169,-0.007623,-0.027261,0.015769,-0.029457,-0.002620,-0.014650,-0.019315,-0.013345,0.001436,0.015538,0.002107,-0.005948,-0.000968,0.014284,0.043325,0.015011,-0.000411,0.002900,0.026704,0.010896,-0.030184,0.010944,0.005637,0.008911,-0.037639,-0.053375,0.004473,0.005451,-0.007650,-0.006180,0.014277,-0.034433,-0.003408,0.012363,0.004979,-0.009885,-0.014503,0.000940,-0.010479,0.030058,-0.060388,0.004867,0.035775,-0.019490,-0.046256,0.005965,-0.000538,0.011405,-0.005275,-0.011199,0.026271,-0.004283,0.023428,0.006830,0.030756,-0.015325,-0.002703,-0.019308,0.013847,0.017578,0.004395,-0.007757,-0.002439,-0.013878,0.013159,0.007227,0.008624,-0.011018,0.017294,-0.048733,-0.008690,0.007969,0.010187,0.013464,0.003348,-0.002086,0.016963,-0.003648,0.013810,0.014049,0.024536,0.010314,0.019225,0.010424,-0.035403,-0.001703,0.022133,0.010746,0.010428,0.030482,0.047542,0.050607,-0.022701,0.002433,-0.004448,0.001610,0.031843,0.030326,0.022789,0.008051,0.021775,-0.025222,0.000076,-0.044165,-0.011388,-0.021275,-0.001946,-0.000309,0.005093,0.042545,0.003667,0.015644,-0.015078,0.005343,0.001526,0.008432,-0.036541,-0.006352,-0.038776,0.019608,-0.003632,0.012458,-0.001097,-0.012566,0.014341,-0.019957

In [17]:
#| code-summary: 'Doc2Vec from Lab 4'
# Prepare Doc2Vec-specific format
train_tagged_docs = [TaggedDocument(spacy_tokenizer(doc), [i]) for i, doc in enumerate(df_train_bal['text'])]
test_tagged_docs = [TaggedDocument(spacy_tokenizer(doc), [i]) for i, doc in enumerate(df_test['text'])]

# Configure and TRAIN Doc2Vec model
X_train_dv_vectors = Doc2Vec(train_tagged_docs, vector_size=300, window=2, min_count=2, epochs=40, seed=42)
X_test_dv_vectors = Doc2Vec(test_tagged_docs, vector_size=300, window=2, min_count=2, epochs=40, seed=42)
X_train_dv = list(X_train_dv_vectors.dv.vectors)
X_test_dv = list(X_test_dv_vectors.dv.vectors)

pd.DataFrame(X_train_dv, index=df_train_bal.index).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299
5903,0.035317,0.320354,-0.926446,0.778507,-0.059755,0.351596,0.315058,0.109383,-0.324056,0.936658,0.734125,0.871844,-0.592808,0.673142,0.609033,0.044005,-1.132675,-0.241563,-0.344555,0.856007,0.708678,-1.025080,0.029638,1.005595,0.361247,0.598653,-0.365538,0.541625,-0.429494,-0.353045,-0.900789,-0.228325,-1.960521,0.330806,0.383495,0.943457,0.420437,-0.285185,-0.743700,-0.375696,0.747443,-0.065201,0.125298,-0.610115,-0.266841,0.936735,-0.462211,-0.553087,0.951625,0.215494,0.299106,-0.287706,1.230846,-0.091514,0.276991,-0.821316,0.640729,0.438131,-0.371039,0.765477,0.031812,0.302615,0.147327,0.945189,0.398307,0.234827,0.562567,-0.203561,-0.140217,-0.037011,-0.281864,-0.235487,-0.508104,-0.624917,0.100906,0.439759,-0.141409,-0.358180,0.379986,-0.176133,-0.843341,0.054825,-0.308751,0.404779,-0.346216,-0.740472,0.031166,-0.039507,-0.226036,0.982705,0.323679,0.541053,-1.103988,-0.579177,-0.126818,-0.179737,-0.112322,0.610579,0.469227,0.170360,-0.943476,0.114566,0.289666,-0.117555,0.709197,0.352069,0.601780,0.341780,-1.231716,0.505367,-0.035452,-0.167084,-0.325946,1.254683,0.369214,0.574016,0.005209,1.287266,0.438763,-0.833610,0.315849,0.893006,1.071789,0.013488,-0.303836,0.382645,-1.517060,-0.083133,0.622597,0.125943,-0.270983,0.132887,0.177424,0.755619,0.337183,1.066224,-0.306400,0.322612,0.191908,-0.500999,0.282045,-0.408476,-0.097679,-0.750726,-0.802931,0.298652,1.372146,0.219836,1.317986,-0.524992,0.261006,0.832178,-0.126161,-1.308103,0.598533,-0.360830,-0.425448,-0.446683,0.367291,-0.267063,1.420334,0.231570,-0.191524,-0.908266,-1.301677,-0.349721,-0.173455,-0.184360,-0.438400,-0.892918,-0.044725,-0.355349,0.145058,-0.003688,0.511485,-0.380218,-0.467191,0.282609,0.267754,0.440329,-0.399576,-0.565247,-0.245982,0.568154,0.755469,-0.138341,0.427678,-1.617154,1.374691,1.015082,0.406480,0.441688,0.546237,-0.504221,-0.894389,-0.035886,-0.139550,-0.441128,0.317120,0.311725,1.361075,-0.742835,-0.087829,-0.936482,0.093331,0.200093,-1.507786,0.504151,0.227964,0.325907,-0.529120,-0.850297,1.126417,-0.915282,-0.346936,-1.020483,-0.397602,0.078668,0.673764,-0.670004,-0.478466,0.225794,1.067223,-0.529117,-0.525636,0.345969,0.945780,0.990379,-0.924881,0.461486,-0.719871,-1.337548,-0.420058,0.005430,0.564849,0.533142,-0.146294,0.674619,-0.710388,-0.974398,-0.516187,0.787815,-0.619477,-1.650251,-0.277016,0.030830,0.186341,-0.592947,0.741486,-0.419233,-0.216435,-1.281538,0.286993,-1.449170,-0.987833,-1.290240,0.808904,-0.720426,0.142199,1.774595,1.108672,0.549016,-0.836152,-0.041443,0.352467,0.239711,-0.194473,0.993187,-0.394312,0.080135,-1.067705,0.003213,-0.149830,-0.752272,0.808738,-1.555710,1.007264,-0.761132,-0.294438,-0.889686,-0.471790,0.771964,0.486710,0.419008,-0.181754,0.565126,0.022265,-0.795735,0.416009,-0.672571,-0.904832,0.443013,1.973624,-0.587153,-0.011289,0.551889,0.469192,-0.789435,0.156678,-0.029855
9826,0.132159,0.539716,-1.052991,-1.080075,-0.682317,-0.275342,2.247579,-0.300276,0.339418,-0.265499,0.190449,0.706985,0.192389,0.733062,-0.371869,-0.614847,0.077822,-0.291119,-1.042963,-1.233677,0.061722,-0.445637,0.077377,-0.190253,1.766327,-0.131877,0.047763,0.106474,0.392335,-0.009726,-0.238421,0.950277,1.299665,0.277038,0.536177,0.917533,0.719112,-1.305952,0.222539,-0.138579,-0.167339,0.932172,-0.153711,0.196840,-0.711870,-0.206288,0.630628,-0.694298,1.268848,-0.421000,-1.398334,-0.274950,1.638742,0.270956,1.180548,-0.873266,0.631230,-0.770093,0.630835,0.758022,-0.270378,-0.733421,0.031523,0.113334,0.149031,0.498516,-0.786623,0.809654,-0.269729,1.057015,-0.631985,0.247647,-0.780464,0.959448,-1.680572,-0.475483,-0.782491,0.544029,0.015523,-0.115829,-0.062185,0.304613,-0.372544,0.166572,-0.027901,-0.128531,-0.999244,-0.703926,-0.297461,-0.308975,-0.621601,0.558542,0.061050,0.194932,-0.401452,0.118894,0.380579,-0.612087,0.808489,-0.247842,-0.707251,-0.006545,1.355511,0.579149,-0.127138,0.839203,0.899440,0.263046,-0.276206,-0.097738,1.502151,-0.459611,0.375530,0.396609,-0.759241,-0.046274,0.033171,-0.728720,-0.280782,-0.435129,0.217674,0.203901,-0.555965,1.071143,-0.162802,-0.364748,-1.286134,0.083201,0.669416,-0.724805,0.949363,-0.492732,0.493028,0.584345,-0.129896,-0.448927,-0.460199,-0.879042,1.767419,-0.355043,0.374112,0.059012,0.525916,0.876509,-0.844307,0.171972,0.010786,0.300022,-0.361004,0.225459,-0.095118,-0.594597,1.348577,0.554268,-0.064071,-0.068180,-0.075864,0.253796,-0.311588,-0.683329,0.038594,-0.501548,0.327731,-0.096773,1.128120,0.307923,0.246050,-0.726904,0.694412,-0.961948,-0.338531,0.400469,0.015687,-0.138125,-0.315158,0.906766,0.211299,-1.207977,0.066132,0.887939,1.557388,-0.863079,-1.116272,0.123963,-0.187387,-0.490350,-0.000651,-1.359192,0.039372,-1.089032,0.518423,-0.418691,-0.305283,-0.010136,0.470730,0.599180,0.424146,-0.210225,-1.246949,-0.771147,-0.960939,0.595787,0.607606,-1.893635,-0.105749,1.043339,-0.835427,0.375131,0.232943,1.080784,-0.814102,0.111647,-0.221738,-0.275982,-0.989372,0.578480,0.523423,-1.659332,1.643643,-0.085523,-0.655024,-0.302178,0.193355,-1.149243,0.186763,0.816021,-0.911177,0.538737,-0.509969,0.719528,-0.323606,0.638815,0.397075,-0.282987,-0.514473,-0.029379,0.617239,-0.308900,0.413508,0.152526,0.217734,0.541939,-0.016054,-0.705792,0.744289,-1.216119,-0.079502,-0.349501,-0.009889,-1.037298,-0.158446,-0.443728,0.132408,-0.803019,0.264325,0.182073,0.514426,-0.511562,-0.090915,-0.461851,0.239483,0.649045,0.876946,0.518508,0.887850,0.309322,-0.469229,0.655363,0.457086,1.589028,0.183826,0.503990,0.007689,-0.084999,-0.065749,1.174921,-0.654599,-0.399600,-0.696909,-0.967507,0.468145,0.056918,0.723323,-0.050867,-0.710564,0.251694,-0.540692,1.165581,-1.156017,-0.593803,-1.336599,-0.259071,-0.917842,-0.431504,1.124552,-0.645384,0.488246,0.167314,0.181437,1.019264
8632,-0.176817,-0.135772,-0.376056,0.928467,-0.416626,-0.537127,0.381277,-0.427561,-0.797381,0.386407,-0.247042,0.150912,-0.067611,1.001623,0.326016,0.431950,-0.562278,-0.347460,-0.696570,-0.288058,0.832284,-0.950488,-0.047824,0.595243,0.240920,0.916614,-0.841577,-0.276166,0.019039,-0.280414,-0.985150,-0.648752,-1.213668,0.539149,0.026143,1.415832,0.159815,0.002552,-0.101419,0.680528,0.761283,0.717839,0.144327,-0.004514,-0.085030,1.015499,-0.223810,-0.227125,0.567830,0.618010,-0.598615,-0.125641,0.338125,-1.250040,0.551724,-0.529344,0.337911,0.154286,0.945152,0.503561,0.419584,0.745498,-0.659384,0.380477,0.207455,0.762088,0.282023,-0.204773,0.127666,-0.040974,-0.524739,-0.520149,-0.419289,0.291915,-0.212299,0.231162,0.132906,0.356202,-0.053447,-0.021275,0.058584,-1.047117,-0.638846,0.602428,0.385190,-0.768266,-0.557331,-0.380830,-0.618567,0.041997,-0.297490,0.238716,-1.075976,-1.197463,0.103414,-0.342163,0.213629,0.576099,-0.003197,0.382675,0.165569,0.080329,0.080940,-0.061232,0.524696,0.046859,0.817740,-0.016676,-0.739843,0.333499,-0.727311,-0.039798,0.530346,1.128783,0.144066,-0.322490,-0.448818,0.779809,-0.492984,-0.952494,0.862512,0.873330,1.114629,0.484379,-0.847267,-0.206627,-0.816727,-0.693358,0.773077,-0.435346,-0.329599,0.860330,0.488284,0.539094,0.030460,0.141773,0.203049,0.072140,0.294348,0.692243,0.729067,-1.540441,-0.022033,0.275938,-0.771173,-0.527375,1.533279,0.980298,0.484729,0.285355,0.260028,0.295685,0.255620,-0.805810,1.090598,-0.639780,-1.028855,0.062649,0.737225,-0.287316,0.324175,0.323959,-0.418798,-0.559753,-0.503854,0.097628,0.037415,-0.166008,0.210357,-1.496993,0.027682,0.378779,1.278109,0.574093,0.096622,0.061081,-0.137026,0.417102,0.700190,0.877255,-0.552112,0.235521,-0.623504,-0.162434,0.360984,0.387664,0.553457,-1.828487,0.645642,0.427427,-0.095894,-0.336538,0.646448,0.103165,-0.615687,-0.116133,-0.439126,-0.132188,-0.508813,0.120682,0.380808,-0.256532,0.396393,-0.713572,-0.481477,0.696168,-0.570998,0.160171,1.021399,0.589509,-0.459766,-1.143754,0.201084,-0.852999,-0.158593,0.154732,-0.685944,0.839559,-0.275958,-0.335701,0.496222,-0.317797,0.465998,-0.648695,-0.158625,0.699970,0.394242,1.105711,-0.925416,0.834687,-0.846955,-0.632287,-0.809600,0.212875,1.084217,-0.492257,-0.502202,-0.086612,-0.301935,-0.492079,-0.706715,1.109598,-0.732748,-0.578443,-0.381604,-0.089336,1.123242,0.257590,1.692720,-0.843757,-0.494255,-0.981092,0.118346,-0.136894,-0.017570,-0.800312,0.874965,-0.439426,-0.285778,0.303001,-0.315143,-0.427180,-1.095824,0.111747,0.179019,0.706789,-0.433448,-0.563488,0.171481,0.199311,-0.548671,0.307003,0.715547,0.379834,0.385402,-1.182132,-0.517310,-0.520145,0.085625,-0.801946,-0.120545,0.395148,-0.192431,0.160932,-0.301427,-0.053270,-0.426460,-0.596230,-0.851951,-0.429507,-0.160429,1.616804,1.605214,-0.494304,-0.468399,0.236726,0.313697,-0.833776,0.483492,-0.404961
3138,-0.792871,0.303643,0.499360,-0.440833,0.075176,-0.135713,0.395057,-0.376600,-1.171520,-0.484394,0.625546,-0.645260,0.438966,-0.028794,0.047806,0.610150,0.448149,-0.306031,-1.180300,-0.537622,0.002559,0.177137,1.525784,1.097923,0.275967,1.618407,0.390529,-0.798483,0.713941,-0.545204,-0.204289,0.041583,0.203457,0.910366,-0.219064,0.940977,0.304040,-0.587403,-0.085228,0.707950,-0.420307,-0.168287,1.062302,0.023609,-0.064703,0.087571,0.275822,-0.545828,0.446714,0.546473,-0.247017,-0.272948,0.908096,-0.555793,0.109020,0.361953,-0.267690,0.019938,0.741714,0.852245,0.303705,-0.480713,0.961082,0.440269,-0.041808,1.089478,-0.428759,0.279573,-0.142012,0.815440,-0.698873,-0.700267,-1.384253,0.251119,-0.356667,0.908722,0.415819,-0.026200,-0.417578,0.726024,0.265056,0.878527,-0.416456,0.161692,0.481048,-0.280423,-0.124613,-0.441516,-1.174611,-0.220069,-0.103978,-0.229604,0.695682,0.253566,0.156330,-0.426083,-0.535310,0.652203,0.406045,-0.035808,0.295841,-0.063798,0.493213,0.971007,-0.286327,-0.851786,0.364396,1.224609,-0.892455,-0.535389,-0.184433,-0.213691,0.247839,-0.662463,-0.010103,0.252076,-0.272899,-0.497527,-0.158966,-0.845598,0.073753,0.949078,1.204591,0.312848,0.461556,-0.055081,-0.554869,0.854252,0.253746,-0.326335,1.200245,1.032454,0.677639,-0.164749,0.224337,0.025497,0.410472,-0.830973,0.439880,1.055826,-0.792596,-0.167646,0.399477,0.325998,0.073953,-0.488273,0.243525,1.127068,0.756944,0.725927,0.496405,-0.466384,0.108473,0.482502,-0.194486,-0.325146,-0.579861,-0.012694,-0.358679,0.057349,0.905391,-0.083169,-0.641661,0.239958,0.614110,0.363406,-0.036781,0.604052,-0.371656,-0.386473,-0.268121,0.158035,-0.144218,0.720842,0.042591,0.487041,-0.362954,-0.512295,0.372504,0.818134,-0.234420,-0.408413,-0.302795,0.045678,-0.446732,-0.829830,-1.288277,-0.670300,0.700647,-0.548283,-0.115544,0.065863,0.222859,0.055798,0.634018,-0.486502,-0.776706,-0.244253,-0.370333,-0.715745,-0.359039,-0.115724,0.138349,-0.103880,-1.174120,0.298098,-1.255314,0.173078,0.759631,0.576696,-0.073984,-0.433479,1.297751,-0.386956,-0.409868,1.610813,-0.292654,-1.072146,-1.392165,0.473626,-0.067697,-0.961380,-0.309627,-0.661221,-1.036960,0.350464,-0.073081,0.084416,0.229380,0.017374,-0.232862,-0.406218,-0.662834,0.153806,0.506315,-0.391458,0.291776,-0.053465,0.468388,0.241189,-0.234762,-0.680349,-0.765894,0.505876,0.273354,-0.056044,-0.328365,-0.641844,0.487395,-1.007915,0.122772,-0.594951,-0.022536,-0.256685,-0.166060,-0.725963,0.967076,-0.410820,-0.044328,0.048810,0.384282,-0.418162,-0.537600,0.464933,1.492925,1.124328,-0.814095,-0.274612,-0.207760,0.731759,0.671655,0.675892,0.028809,-0.334033,0.052216,0.851290,-0.560107,-0.003611,-0.225226,-1.087631,0.400628,0.458759,0.261132,-0.611961,-1.056542,-0.591103,-0.470527,-0.143774,-2.045030,0.348883,0.146761,0.432916,0.489484,-0.408967,0.781826,0.312137,0.562539,-0.219022,0.569497,0.482420
9381,0.113926,-0.396603,-0.371444,0.276578,-0.255914,-0.441716,-0.325734,-0.091228,-0.843206,0.785255,0.726934,0.832956,0.327051,0.284094,-0.183887,0.211569,-0.575848,0.414578,-1.229762,-0.462176,0.669904,-0.290874,0.605848,0.555630,0.101588,0.231734,-0.409687,-0.150561,0.032136,0.295042,-1.467405,-0.536050,-0.989183,0.093063,0.074196,0.697043,0.463135,-0.650633,-0.010854,0.044758,1.770649,-0.384418,-0.749630,-0.191240,0.001222,0.950302,-0.851526,-0.322611,0.675029,0.415011,-0.503729,0.183305,0.875001,-0.863066,0.788164,-0.090582,0.251520,-0.245610,0.712406,0.415868,0.308355,1.060222,-1.464332,0.402206,-0.478835,0.819368,0.061915,-0.053410,0.141804,-0.342757,-0.033484,0.007731,-0.766867,0.103855,0.191449,0.154887,0.265278,0.342675,0.386118,-0.422609,0.153601,0.064008,-0.108384,0.673647,-0.549664,-1.026050,-0.045218,-0.096219,-0.044343,0.139766,-0.165685,1.162851,-1.092488,0.347825,-0.095065,0.360473,-0.219452,0.297398,-0.811929,0.419894,-0.035615,-0.165251,-0.183083,-0.341875,-0.200373,-0.429157,-0.427329,0.746415,-0.561975,-0.271005,-0.646587,-0.317499,0.248823,1.135674,0.172112,0.370103,-0.260481,0.902441,0.183429,-0.947208,0.679295,1.089068,0.010046,-0.041860,0.683180,0.000102,-0.285805,-0.644286,0.056962,0.038922,0.176158,0.712123,0.345126,0.328424,0.288058,-0.156478,-0.751103,0.768083,0.299124,0.015819,0.199547,-1.468589,0.145092,0.423161,-0.407192,-0.017791,0.397351,1.094436,0.441771,0.415882,0.675620,-1.000016,-0.209414,-0.227502,0.729052,-0.580346,-0.315941,-0.313950,1.169344,-0.451127,0.126568,0.534703,0.113197,0.120563,0.249190,-0.007660,-0.104983,0.002429,0.475319,-1.057976,-0.636878,0.415123,1.144057,0.084403,0.484841,-0.026532,-0.316709,-0.165006,-0.144623,0.785713,0.002249,-0.164636,0.213399,0.669452,1.204489,0.318622,1.064413,-0.421372,1.458470,-0.474972,-0.166922,0.280527,0.644282,-0.251067,0.012064,0.020128,-0.420888,0.396111,0.017212,0.425061,0.207519,-0.395583,-0.066777,-0.800933,0.049612,0.378499,-0.929154,0.919784,0.151681,0.701333,0.027308,-0.827803,0.010996,0.256653,0.278211,-0.507375,-0.098286,0.274401,-0.083843,0.059978,-0.469083,-0.535101,0.406000,-0.480960,0.074659,0.586449,0.533126,0.761458,-0.300392,-0.017629,-1.048055,-0.862840,-0.321361,0.643560,0.247004,0.242725,-0.311391,-0.136152,-0.603469,-0.855216,-0.877818,0.895750,-0.427291,-0.320578,-0.424335,-0.220830,0.715805,0.501418,0.447090,-0.297213,0.000811,-0.323254,-0.268928,-0.948012,0.112950,-0.602755,-0.167071,-0.633401,-0.547554,0.167430,0.340333,-0.183256,-0.545481,0.272691,-0.269109,0.373696,0.132974,0.194516,-0.600816,0.403609,-0.360487,0.046205,1.055842,-0.945860,-0.012303,-0.915363,0.288871,-0.486957,-0.062779,-0.321982,0.017765,0.221626,-0.118309,-0.139459,-0.815185,0.360736,-0.583166,-0.810456,-0.539851,-0.252521,0.000971,0.878010,1.478095,0.292343,-0.264042,-0.069466,0.177680,-0.509294,0.531623,-0.436715

# Modeling

In [18]:
#| code-summary: 'Data preparation for modeling'
y_train = df_train_bal['y']
y_test = df_test['y']
pos_label = 1 # check 'y'
average = 'macro' # 'binary' (2-class), 'macro' (N-class)
df_res = pd.DataFrame(columns=['Representation', 'Model', 'Accuracy', 'Precision', 'Recall', 'F1'])

## Naive Bayes

In [19]:
#| code-summary: 'Function to train and evaluate Naive Bayes'
def train_eval_mnb(X_train, y_train, X_test, y_test, representation, pos_label, average):
    '''docstring'''
    grid = GridSearchCV(
        MultinomialNB(),
        param_grid={'alpha': [0.01, 0.1, 0.5, 1, 2, 5]},
        cv=5,
        scoring=make_scorer(f1_score, pos_label=pos_label, average=average)
    )
    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_
    
    # Evaluate on held-out test data
    y_pred = best_model.predict(X_test)
    metrics = [
        round(accuracy_score(y_test, y_pred), 2),
        round(precision_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(recall_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(f1_score(y_test, y_pred, pos_label=pos_label, average=average), 2)
    ]
    return [representation, 'Naive Bayes'] + metrics

def train_eval_gnb(X_train, y_train, X_test, y_test, representation, pos_label, average):
    '''docstring'''
    grid = GridSearchCV(
        GaussianNB(),
        param_grid={'var_smoothing': [1e-11, 1e-10, 1e-9, 1e-8, 1e-7]},
        cv=5,
        scoring=make_scorer(f1_score, pos_label=pos_label, average=average)
    )
    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_
    
    # Evaluate on held-out test data
    y_pred = best_model.predict(X_test)
    metrics = [
        round(accuracy_score(y_test, y_pred), 2),
        round(precision_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(recall_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(f1_score(y_test, y_pred, pos_label=pos_label, average=average), 2)
    ]
    return [representation, 'Naive Bayes'] + metrics

In [20]:
#| code-summary: 'Run for all representations and report in DataFrame'
df_res.loc[len(df_res)] = train_eval_mnb(X_train_bow, y_train, X_test_bow, y_test, 'Bag of Words', pos_label, average)
df_res.loc[len(df_res)] = train_eval_mnb(X_train_tfidf, y_train, X_test_tfidf, y_test, 'TF-IDF', pos_label, average)
df_res.loc[len(df_res)] = train_eval_gnb(X_train_mean_wv, y_train, X_test_mean_wv, y_test, 'Word2Vec', pos_label, average)
df_res.loc[len(df_res)] = train_eval_gnb(X_train_dv, y_train, X_test_dv, y_test, 'Doc2Vec', pos_label, average)
df_res

c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:

  Representation        Model  Accuracy  Precision  Recall    F1
0   Bag of Words  Naive Bayes      0.91       0.92    0.91  0.91
1         TF-IDF  Naive Bayes      0.91       0.92    0.91  0.91
2       Word2Vec  Naive Bayes      0.88       0.88    0.88  0.88
3        Doc2Vec  Naive Bayes      0.62       0.62    0.62  0.62

## Logistic Regression

In [21]:
#| code-summary: 'Function to train and evaluate Logistic Regression'
def train_eval_logr(X_train, y_train, X_test, y_test, representation, pos_label, average):
    '''docstring'''
    grid = GridSearchCV(
        LogisticRegression(max_iter=1000),
        param_grid={'C': [0.01, 0.1, 1, 10, 100]},
        cv=5,
        scoring=make_scorer(f1_score, pos_label=pos_label, average=average)
    )
    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_
    
    # Evaluate on held-out test data
    y_pred = best_model.predict(X_test)
    metrics = [
        round(accuracy_score(y_test, y_pred), 2),
        round(precision_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(recall_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(f1_score(y_test, y_pred, pos_label=pos_label, average=average), 2)
    ]
    return [representation, 'Logistic Regression'] + metrics

In [22]:
#| code-summary: 'Run for all representations and report in DataFrame'
df_res.loc[len(df_res)] = train_eval_logr(X_train_bow, y_train, X_test_bow, y_test, 'Bag of Words', pos_label, average)
df_res.loc[len(df_res)] = train_eval_logr(X_train_tfidf, y_train, X_test_tfidf, y_test, 'TF-IDF', pos_label, average)
df_res.loc[len(df_res)] = train_eval_logr(X_train_mean_wv, y_train, X_test_mean_wv, y_test, 'Word2Vec', pos_label, average)
df_res.loc[len(df_res)] = train_eval_logr(X_train_dv, y_train, X_test_dv, y_test, 'Doc2Vec', pos_label, average)
df_res

c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:

  Representation                Model  Accuracy  Precision  Recall    F1
0   Bag of Words          Naive Bayes      0.91       0.92    0.91  0.91
1         TF-IDF          Naive Bayes      0.91       0.92    0.91  0.91
2       Word2Vec          Naive Bayes      0.88       0.88    0.88  0.88
3        Doc2Vec          Naive Bayes      0.62       0.62    0.62  0.62
4   Bag of Words  Logistic Regression      0.97       0.97    0.97  0.97
5         TF-IDF  Logistic Regression      0.94       0.94    0.94  0.94
6       Word2Vec  Logistic Regression      0.83       0.83    0.83  0.83
7        Doc2Vec  Logistic Regression      0.55       0.65    0.56  0.47

## Linear SVC

In [23]:
#| code-summary: 'Function to train and evaluate linear SVM'
def train_eval_lsvc(X_train, y_train, X_test, y_test, representation, pos_label, average, random_seed):
    '''docstring'''
    grid = GridSearchCV(
        LinearSVC(random_state=random_seed, max_iter=5000),
        param_grid={'C': [0.01, 0.1, 1, 10, 100]},
        cv=5,
        scoring=make_scorer(f1_score, pos_label=pos_label, average=average)
    )
    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_
    
    # Evaluate on held-out test data
    y_pred = best_model.predict(X_test)
    metrics = [
        round(accuracy_score(y_test, y_pred), 2),
        round(precision_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(recall_score(y_test, y_pred, pos_label=pos_label, average=average), 2),
        round(f1_score(y_test, y_pred, pos_label=pos_label, average=average), 2)
    ]
    return [representation, 'Linear SVM'] + metrics

In [24]:
#| code-summary: 'Run for all representations and report in DataFrame'
df_res.loc[len(df_res)] = train_eval_lsvc(X_train_bow, y_train, X_test_bow, y_test, 'Bag of Words', pos_label, average, RANDOM_SEED)
df_res.loc[len(df_res)] = train_eval_lsvc(X_train_tfidf, y_train, X_test_tfidf, y_test, 'TF-IDF', pos_label, average, RANDOM_SEED)
df_res.loc[len(df_res)] = train_eval_lsvc(X_train_mean_wv, y_train, X_test_mean_wv, y_test, 'Word2Vec', pos_label, average, RANDOM_SEED)
df_res.loc[len(df_res)] = train_eval_lsvc(X_train_dv, y_train, X_test_dv, y_test, 'Doc2Vec', pos_label, average, RANDOM_SEED)
df_res

c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\svm\_base.py:1295: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(
c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 328, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\hertie\Sem 5\NLP\NLP_labs_personal\.venv\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['human' 'machine']

  warnings.warn(

   Representation                Model  Accuracy  Precision  Recall    F1
0    Bag of Words          Naive Bayes      0.91       0.92    0.91  0.91
1          TF-IDF          Naive Bayes      0.91       0.92    0.91  0.91
2        Word2Vec          Naive Bayes      0.88       0.88    0.88  0.88
3         Doc2Vec          Naive Bayes      0.62       0.62    0.62  0.62
4    Bag of Words  Logistic Regression      0.97       0.97    0.97  0.97
5          TF-IDF  Logistic Regression      0.94       0.94    0.94  0.94
6        Word2Vec  Logistic Regression      0.83       0.83    0.83  0.83
7         Doc2Vec  Logistic Regression      0.55       0.65    0.56  0.47
8    Bag of Words           Linear SVM      0.96       0.96    0.97  0.96
9          TF-IDF           Linear SVM      0.94       0.95    0.94  0.94
10       Word2Vec           Linear SVM      0.84       0.84    0.84  0.84
11        Doc2Vec           Linear SVM      0.52       0.57    0.53  0.45